package om.entities;
// Generated Oct 18, 2016 8:15:36 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bid generated by hbm2java
 */
@Entity
@Table(name = "bid", catalog = "bid_system")
public class Bid implements java.io.Serializable {

	private Integer id;
	private Item item;
	private User user;
	private boolean isRecent;
	private int bidAmount;
	private boolean bidWon;
	private Date bidTime;

	public Bid() {
	}

	public Bid(boolean isRecent, int bidAmount) {
		this.isRecent = isRecent;
		this.bidAmount = bidAmount;
	}

	public Bid(Item item, User user, boolean isRecent, int bidAmount, boolean bidWon) {
		this.item = item;
		this.user = user;
		this.isRecent = isRecent;
		this.bidAmount = bidAmount;
		this.bidWon = bidWon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "is_recent", nullable = false)
	public boolean isIsRecent() {
		return this.isRecent;
	}

	public void setIsRecent(boolean isRecent) {
		this.isRecent = isRecent;
	}

	@Column(name = "bid_amount", nullable = false)
	public int getBidAmount() {
		return this.bidAmount;
	}

	public void setBidAmount(int bidAmount) {
		this.bidAmount = bidAmount;
	}

	@Column(name = "bid_won")
	public boolean isBidWon() {
		return this.bidWon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bid_time", length = 19)
	public Date getBidTime() {
		return this.bidTime;
	}

	public void setBidTime(Date bidTime) {
		this.bidTime = bidTime;
	}

	public void setBidWon(boolean bidWon) {
		this.bidWon = bidWon;
	}

}
